spring:
  application:
    name: user-service
  profiles:
    default: dev
  jpa:
    open-in-view: false

server:
  port: 8081
  error:
    include-stacktrace: never

app:
  jwt:
    expiration-minutes: 60
    issuer: bookstore
