-- V1 — payment-service's schema, in its own database.

CREATE TABLE payment (
    id             BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- UNIQUE, and this constraint is the entire duplicate-charge defence.
    --
    -- payment-service and order-service share no transaction, so a repeated request is always
    -- possible: a lost response, a double-submitted form, a proxy replay. Every one of them ends here,
    -- and the database decides. An application-level "have we paid already?" check has a gap between
    -- the check and the insert that two concurrent requests fit through.
    --
    -- Not a foreign key: orders live in another service's database (D5).
    order_id       BIGINT         NOT NULL UNIQUE,

    user_id        BIGINT         NOT NULL,
    amount         NUMERIC(12, 2) NOT NULL,
    status         VARCHAR(20)    NOT NULL,
    paid_at        TIMESTAMPTZ    NOT NULL,

    -- Whether order-service has been told. The money moving and the order changing state are two
    -- writes in two databases; this is what lets recovery find the ones whose second write never
    -- landed. Same write-it-down-first principle as the order saga, other end of the conversation.
    order_notified BOOLEAN        NOT NULL DEFAULT FALSE,

    CONSTRAINT payment_status_valid CHECK (status IN ('SUCCESS', 'FAILED')),
    CONSTRAINT payment_amount_non_negative CHECK (amount >= 0)
);

-- The recovery job's query: successful payments order-service does not know about.
CREATE INDEX idx_payment_unnotified ON payment (status, order_notified)
    WHERE order_notified = FALSE;
