-- V1 — the initial schema.
--
-- This is the same `book` table Hibernate used to generate from the entity under ddl-auto, now written
-- out by hand and owned by us. From here on Hibernate only *validates* that the entity matches this
-- table; it never alters it.
--
-- Schema only — no sample data. Demo rows live in db/seed/ and are loaded under the dev profile alone,
-- so they can never reach production.

CREATE TABLE book (
    id         BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(255)   NOT NULL,
    isbn       VARCHAR(255)   UNIQUE,
    price      NUMERIC(10, 2) NOT NULL,
    stock      INTEGER        NOT NULL,
    cover_url  VARCHAR(255),
    version    BIGINT,
    created_at TIMESTAMPTZ    NOT NULL,

    -- Enforced by the database, not just by the application. Bean Validation on the DTO can be
    -- bypassed (a bad migration, a manual UPDATE, a second service later); this constraint cannot.
    CONSTRAINT book_stock_non_negative CHECK (stock >= 0)
);
