-- V2 — authors, and the book -> author relation.

CREATE TABLE author (
    id   BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

-- Nullable on purpose: rows already in `book` have no author yet, and a NOT NULL column cannot be
-- added to a populated table without a default or a backfill.
ALTER TABLE book ADD COLUMN author_id BIGINT;

ALTER TABLE book
    ADD CONSTRAINT fk_book_author FOREIGN KEY (author_id) REFERENCES author (id);
