-- V4 — application users.

CREATE TABLE users (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL UNIQUE,
    email         VARCHAR(255) NOT NULL UNIQUE,

    -- A BCrypt hash, never a password. The column is named for what it holds so that no one reading
    -- the schema can mistake it for the real thing. BCrypt output is always 60 characters.
    password_hash VARCHAR(100) NOT NULL,

    role          VARCHAR(20)  NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL,

    CONSTRAINT users_role_valid CHECK (role IN ('USER', 'ADMIN'))
);

-- The table is called `users`, not `user`: USER is a reserved word in PostgreSQL (it returns the
-- current session user), so `SELECT * FROM user` does not mean what it looks like.

-- Login reads by username on every request that authenticates, so it has to be indexed. The UNIQUE
-- constraint above already creates that index — declaring another would be pure write cost.
