-- A dev-only ADMIN account, so the admin-protected endpoints can be exercised locally.
--
-- Lives in db/seed/, which only application-dev.yml loads (see D7) — this account cannot reach
-- production. Repeatable and idempotent for the same reasons as the sample books.
--
--   username: admin
--   password: admin-dev-password
--
-- The hash below is a genuine BCrypt hash of that password, generated by this application. Publishing
-- it costs nothing: the password is public in this very comment, and the account exists only in a
-- throwaway local database. Real credentials are never committed — the prod profile takes them from the
-- environment.
--
-- Registration deliberately cannot create an ADMIN (see RegisterRequestDto), so seeding one is the only
-- way to get the first admin. In a real deployment that bootstrap is normally a one-off migration or an
-- operator command, and the account's password is rotated immediately after.

INSERT INTO users (username, email, password_hash, role, created_at)
VALUES (
    'admin',
    'admin@example.com',
    '$2a$10$W5MS59odb6CmTU14MCLiiO1/KCECLdCDE62FrZGm8T5Sxh7mJEsIK',
    'ADMIN',
    NOW()
)
ON CONFLICT (username) DO NOTHING;
