-- V1 — user-service's schema, in its own database.
--
-- This service's migration history starts at V1 even though the monolith reached V5: a new database
-- has no history to replay, so the schema is written as it should be rather than as it became. The
-- monolith's V1-V5 remain in Git at the step-4-monolith tag.

CREATE TABLE users (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL UNIQUE,
    email         VARCHAR(255) NOT NULL UNIQUE,
    -- A BCrypt hash, never a password. BCrypt output is always 60 characters.
    password_hash VARCHAR(100) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL,

    CONSTRAINT users_role_valid CHECK (role IN ('USER', 'ADMIN'))
);

-- `users`, not `user`: USER is a reserved word in PostgreSQL — SELECT * FROM user returns the session
-- user, not the table.
--
-- No extra index on username: the UNIQUE constraint already creates one, and login reads by username on
-- every authentication.
