-- V1 — book-service's schema, in its own database.
--
-- The monolith reached this shape over five migrations (V1 create, V2 author, V3 indexes, V5 version
-- default). A new database has no history to replay, so the schema is written as it should be rather
-- than as it became. The monolith's migrations remain in Git at the step-4-monolith tag.
--
-- Note what is NOT here: no users table. book-service cannot read a user even if it wants to — that is
-- Database-per-Service, enforced by there being no such table and no credentials for the other
-- database. See D5.

CREATE TABLE author (
    id   BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE book (
    id         BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(255)   NOT NULL,
    isbn       VARCHAR(255)   UNIQUE,
    author_id  BIGINT         REFERENCES author (id),
    price      NUMERIC(10, 2) NOT NULL,
    stock      INTEGER        NOT NULL,
    cover_url  VARCHAR(255),

    -- NOT NULL DEFAULT 0 from the start. In the monolith this was nullable, and a row inserted by
    -- plain SQL landed with NULL, so the first optimistic-locking update of that row failed on the
    -- increment. Fixed there in V5; correct here from V1.
    version    BIGINT         NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ    NOT NULL,

    -- Enforced by the database, not only by Bean Validation on the DTO: a constraint cannot be raced,
    -- bypassed by a manual UPDATE, or forgotten by a future caller.
    CONSTRAINT book_stock_non_negative CHECK (stock >= 0)
);

-- PostgreSQL indexes a PRIMARY KEY automatically but NOT a FOREIGN KEY column. This one is filtered on,
-- joined on, and read by the referential check that runs on every DELETE FROM author.
CREATE INDEX idx_book_author_id ON book (author_id);

-- Exact matches and prefix search. A B-tree is ordered, so it can seek to a known prefix.
CREATE INDEX idx_book_title ON book (title);

-- A B-tree cannot serve LIKE '%keyword%' — it is sorted by the start of the string and a leading
-- wildcard leaves no start to seek to. pg_trgm indexes every three-character sequence instead.
-- The expression must match the query's exactly, hence lower(title): see D10.
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX idx_book_title_trgm ON book USING GIN (lower(title) gin_trgm_ops);
