spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/paymentdb
    username: paymentdb
    password: paymentdb
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    locations: classpath:db/migration
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 2000
            read-timeout: 3000

app:
  order-service:
    url: http://localhost:8083
  jwt:
    secret: w4HvWMieqVUX1LJpx/wVR+yANNMPgD/dwfEySBsQuZyr7nej+tEV7aZkrzB12Ip3

logging:
  level:
    com.example: DEBUG
