-- V1 — order-service's schema, in its own database.

CREATE TABLE orders (
    id          BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- The customer, from the token's `uid` claim. NOT a foreign key: the users table lives in another
    -- service's database that this service has no credentials for. The database can no longer check
    -- that this refers to a real person — that guarantee comes from the token's signature (D5).
    user_id     BIGINT         NOT NULL,

    status      VARCHAR(20)    NOT NULL,
    total_price NUMERIC(12, 2) NOT NULL,
    version     BIGINT         NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ    NOT NULL,

    CONSTRAINT orders_status_valid CHECK (status IN ('PENDING', 'PAID', 'CANCELLED', 'SHIPPED')),
    CONSTRAINT orders_total_non_negative CHECK (total_price >= 0)
);

CREATE TABLE order_item (
    id         BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- This one IS a foreign key: both tables live here, so the database can and should enforce it.
    -- The contrast with user_id above is the whole of Database-per-Service in two columns.
    order_id   BIGINT         NOT NULL REFERENCES orders (id) ON DELETE CASCADE,

    book_id    BIGINT         NOT NULL,

    -- Denormalised from book-service at order time. Rendering an order must not require the catalog to
    -- be up, and must show what was actually bought rather than what the book is called today.
    book_title VARCHAR(255)   NOT NULL,

    quantity   INTEGER        NOT NULL,

    -- The price paid, captured then. Never re-read: a price change must not alter a past receipt.
    unit_price NUMERIC(10, 2) NOT NULL,

    CONSTRAINT order_item_quantity_positive CHECK (quantity > 0),
    CONSTRAINT order_item_price_non_negative CHECK (unit_price >= 0)
);

-- "Show me my orders" runs on every visit to the account page; without this it is a full scan.
CREATE INDEX idx_orders_user_id ON orders (user_id);

-- Loading an order's lines, and the referential check on every DELETE FROM orders.
CREATE INDEX idx_order_item_order_id ON order_item (order_id);
